### ISSUE TITLE
More model training code

### ISSUE THREAD

**Issue by zstBUPT** [YuchuanTian/AIGC_text_detector#10]
would you share the training codes of several other existing method(like GLTR, PPL, OpenAI, DetectGPT, RoBERTa-Stylo) on the HC3-En-Sent data set?

**Comment by YuchuanTian** [comment]
Hi, thank you for your interest in our work!

For GLTR/PPL/DetectGPT: these methods are zero-shot methods that does not require training. Please refer to the official repo and plug the HC3-En-Sent dataset into these models.
For OpenAI: this is a pretrained opensourced detector. Please directly download the model for inference.
For RoBERTa-Stylo: we apologize for not being able to provide the code because these codes are in corporate devices... But I think it would be easy to re-implement it by plugging its official implementation to the detector model in our training codebase. The training hyperparameters are the same with our setting.

Hope my response helps!

**Comment by zstBUPT** [comment]
Okay, thank you very much for your positive reply. It is very meaningful work. I look forward to your future work.  :)

**Comment by YuchuanTian** [comment]
Thank you too!
